// lib/order_confirmation_page.dart
import 'package:flutter/material.dart';
import 'package:webshop/products_screen.dart';

/// Displays the success screen after a completed order.
///
/// This page provides immediate feedback to the user that their transaction
/// was processed successfully. It displays the unique [orderId] generated by
/// the backend and the [finalAmountPaid].
///
/// It acts as the terminal point of the checkout flow, preventing users from
/// navigating back to the payment screen.
class OrderConfirmationPage extends StatelessWidget {
  /// The unique identifier assigned to the order (usually from Firestore/Cloud Functions).
  final String orderId;

  /// The total amount actually charged to the user (after any gift card discounts).
  final double finalAmountPaid;

  /// Creates an [OrderConfirmationPage].
  const OrderConfirmationPage({
    super.key,
    required this.orderId,
    required this.finalAmountPaid,
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Order Confirmation'),
        // UX PATTERN: We explicitly hide the back button.
        // Once an order is confirmed, the "checkout session" is over.
        // Allowing the user to go back to the Payment Page could lead to
        // confusion or accidental double payments.
        automaticallyImplyLeading: false,
      ),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              // Visual Success Indicator
              const Icon(
                Icons.check_circle_outline,
                color: Colors.green,
                size: 100,
              ),
              const SizedBox(height: 20),

              const Text(
                'Order Placed Successfully!',
                style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 10),

              // Order Details
              Text(
                'Your Order ID: #$orderId',
                style: const TextStyle(fontSize: 18),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 5),

              Text(
                'Total Paid: €${finalAmountPaid.toStringAsFixed(2)}',
                style:
                    const TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 30),

              // Navigation Reset Button
              ElevatedButton(
                onPressed: () {
                  // NAVIGATION RESET:
                  // We use [pushAndRemoveUntil] to wipe the entire navigation history.
                  // This ensures that when the user clicks "Continue Shopping":
                  // 1. They go to the Home Screen (ProductsScreen).
                  // 2. The "Back" button on the phone will exit the app instead of
                  //    taking them back to this confirmation page.
                  Navigator.of(context).pushAndRemoveUntil(
                    MaterialPageRoute(
                        builder: (context) => const ProductsScreen()),
                    (Route<dynamic> route) => false,
                  );
                },
                child: const Text('Continue Shopping'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
